#ifndef TEXTURE_H
#define TEXTURE_H

#include <QtOpenGL/QtOpenGL>
#include <string>

class Texture
{
    GLuint tex; ///< The texture id generated by glGenTexture2D
    bool loaded;

public:
    Texture();
    void loadFromFile(const std::string &filename);
    void loadFromFile(const char *filename);
    void loadFromData(GLsizei width, GLsizei height, const GLvoid* data);
    void loadEmpty(unsigned int width, unsigned int height);
    void clearTexture();
    GLuint getTexture() const {return tex;}
    bool isReady() { return loaded; };
};

#endif // TEXTURE_H
